# Complete Manifest Where in single yml we defined Deployment & Service for SpringApp & PVC(with default  StorageClass),ReplicaSet & Service For Mongo.
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: directory
  name: addressbook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: addressbook
  template:
    metadata:
      name: addressbook
      labels:
        app: addressbook
    spec:
      containers:
        - name: addressbook-container
          image: 322266404742.dkr.ecr.us-west-2.amazonaws.com/addressbook:1.2.0
          ports:
            - containerPort: 8080
